"""empty message

Revision ID: 12e6cefb9607
Revises: 
Create Date: 2023-05-08 19:28:55.995657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e6cefb9607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dogPhoto', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint(None, ['dogPhoto'])
        batch_op.drop_column('photo')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userPhoto', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint(None, ['userPhoto'])
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('userPhoto')

    with op.batch_alter_table('Dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dogPhoto')

    # ### end Alembic commands ###
