"""empty message

Revision ID: 5ab9296381b3
Revises: 
Create Date: 2023-05-04 11:23:04.994492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab9296381b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=350), nullable=False),
    sa.Column('title', sa.String(length=35), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('title')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('lastName', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('province', sa.String(length=35), nullable=False),
    sa.Column('postalCode', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('aboutMe', sa.String(length=300), nullable=True),
    sa.Column('birthdate', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('photo')
    )
    op.create_table('Dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dogName', sa.String(length=35), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('dogBirth', sa.String(length=20), nullable=False),
    sa.Column('dogSex', sa.String(length=20), nullable=False),
    sa.Column('dogSize', sa.String(length=20), nullable=True),
    sa.Column('neutered', sa.Boolean(), nullable=False),
    sa.Column('socialCats', sa.Boolean(), nullable=False),
    sa.Column('socialKids', sa.Boolean(), nullable=False),
    sa.Column('socialDogs', sa.Boolean(), nullable=False),
    sa.Column('microchip', sa.BigInteger(), nullable=False),
    sa.Column('dogActivity', sa.String(length=20), nullable=True),
    sa.Column('observations', sa.String(length=500), nullable=True),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microchip'),
    sa.UniqueConstraint('photo')
    )
    op.create_table('Tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['Services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('hourPick', sa.String(), nullable=False),
    sa.Column('hourDeliver', sa.String(), nullable=False),
    sa.Column('dogsAcepted', sa.Integer(), nullable=False),
    sa.Column('dogIdAcepted', sa.Integer(), nullable=False),
    sa.Column('acepted', sa.Boolean(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=True),
    sa.Column('tarif_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tarif_id'], ['Tariffs.id'], ),
    sa.ForeignKeyConstraint(['user_from_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Books')
    op.drop_table('Tariffs')
    op.drop_table('Dog')
    op.drop_table('User')
    op.drop_table('Services')
    # ### end Alembic commands ###
