"""empty message

<<<<<<<< HEAD:migrations/versions/5790e5a28214_.py
Revision ID: 5790e5a28214
Revises: 
Create Date: 2023-05-01 16:41:10.472933
========
Revision ID: 65aefb332321
Revises: 
Create Date: 2023-05-03 10:11:52.057097
>>>>>>>> fc5da3faf82f754b46654778c579d86aa89c9c19:migrations/versions/65aefb332321_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/5790e5a28214_.py
revision = '5790e5a28214'
========
revision = '65aefb332321'
>>>>>>>> fc5da3faf82f754b46654778c579d86aa89c9c19:migrations/versions/65aefb332321_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=350), nullable=False),
    sa.Column('title', sa.String(length=35), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('title')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('lastName', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('province', sa.String(length=35), nullable=False),
    sa.Column('postalCode', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('aboutMe', sa.String(length=300), nullable=True),
    sa.Column('birthdate', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('photo')
    )
    op.create_table('Dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dogName', sa.String(length=35), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('dogBirth', sa.String(length=20), nullable=False),
    sa.Column('dogSex', sa.String(length=20), nullable=False),
    sa.Column('dogSize', sa.String(length=20), nullable=True),
    sa.Column('neutered', sa.Boolean(), nullable=False),
    sa.Column('socialCats', sa.Boolean(), nullable=False),
    sa.Column('socialKids', sa.Boolean(), nullable=False),
    sa.Column('socialDogs', sa.Boolean(), nullable=False),
    sa.Column('microchip', sa.Integer(), nullable=False),
    sa.Column('dogActivity', sa.String(length=20), nullable=True),
    sa.Column('observations', sa.String(length=500), nullable=True),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microchip'),
    sa.UniqueConstraint('photo')
    )
    op.create_table('Tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['Services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tariffs')
    op.drop_table('Dog')
    op.drop_table('User')
    op.drop_table('Services')
    # ### end Alembic commands ###
