"""empty message

Revision ID: 934e71b54554
Revises: 
Create Date: 2023-04-28 15:58:29.775392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934e71b54554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=35), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('dog_size', sa.String(length=20), nullable=True),
    sa.Column('sterilized', sa.Boolean(), nullable=False),
    sa.Column('social_cats', sa.Boolean(), nullable=False),
    sa.Column('social_kids', sa.Boolean(), nullable=False),
    sa.Column('social_dogs', sa.Boolean(), nullable=False),
    sa.Column('microchip', sa.Integer(), nullable=False),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('observations', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microchip')
    )
    op.create_table('Services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=350), nullable=False),
    sa.Column('title', sa.String(length=35), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('title')
    )
    op.create_table('Tarifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('services_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['services_id'], ['Services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tarifs')
    op.drop_table('Services')
    op.drop_table('Dog')
    op.drop_table('User')
    # ### end Alembic commands ###
